name: movieticket_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - setuptools
  - wheel
  - certifi
  - numpy
  - pandas
  - flask
  - tensorflow
  - pip:
      - absl-py
      - aiofiles
      - aiohttp
      - alembic
      - apscheduler
      - astor
      - async-generator
      - async-timeout
      - attrs
      - boto3
      - botocore
      - bz2file
      - cachetools
      - cffi
      - chardet
      - click
      - cloudpickle
      - colorama
      - colorclass
      - coloredlogs
      - colorhash
      - configargparse
      - cryptography
      - cycler
      - decorator
      - dill
      - dnspython
      - docopt
      - docutils
      - dopamine-rl
      - faker
      - fbmessenger
      - flask
      - future
      - gast
      - gevent
      - gin-config
      - gitdb
      - gitpython
      - google-api-core
      - google-api-python-client
      - google-auth
      - google-auth-httplib2
      - google-auth-oauthlib
      - google-pasta
      - googleapis-common-protos
      - greenlet
      - grpcio
      - gunicorn
      - gym
      - h5py
      - httplib2
      - httptools
      - humanfriendly
      - idna
      - importlib-metadata
      - isodate
      - itsdangerous
      - jinja2
      - jmespath
      - joblib
      - jsonpickle
      - jsonschema
      - kafka-python
      - keras-applications
      - keras-preprocessing
      - kiwisolver
      - mako
      - markdown
      - markupsafe
      - matplotlib
      - mpmath
      - multidict
      - networkx
      - oauth2client
      - oauthlib
      - opencv-python
      - opt-einsum
      - packaging
      - pika
      - pillow
      - promise
      - protobuf
      - psycopg2-binary
      - pyasn1
      - pyasn1-modules
      - pycparser
      - pydot
      - pyglet
      - pyjwt
      - pykwalify
      - pymongo
      - pyparsing
      - pypng
      - pyqrcode
      - pyrsistent
      - pysocks
      - python-crfsuite
      - python-dateutil
      - python-engineio
      - python-socketio
      - python-telegram-bot
      - pytz
      - pyyaml
      - questionary
      - rasa
      - rasa-sdk
      - redis
      - requests
      - requests-oauthlib
      - rocketchat-api
      - rsa
      - ruamel-yaml
      - ruamel-yaml-clib
      - s3transfer
      - sanic
      - sanic-cors
      - sanic-jwt
      - sanic-plugins-framework
      - scikit-learn
      - scipy
      - six
      - slackclient
      - smmap
      - sqlalchemy
      - sympy
      - tabulate
      - tensor2tensor
      - tensorboard
      - tensorflow
      - tensorflow-addons
      - tensorflow-datasets
      - tensorflow-estimator
      - tensorflow-gan
      - tensorflow-hub
      - tensorflow-metadata
      - tensorflow-probability
      - termcolor
      - tqdm
      - twilio
      - tzlocal
      - uritemplate
      - urllib3
      - wcwidth
      - webexteamssdk
      - websocket-client
      - websockets
      - werkzeug
      - wrapt
      - yarl
      - zipp
